# coding: utf-8
"""
    Lightdash API

    API spec for Lightdash server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightdash.com
    Generated by: https://openapi-generator.tech
"""
import unittest

import lightdash_client
from lightdash_client import configuration
from lightdash_client.model.lightdash_user import LightdashUser


class TestLightdashUser(unittest.TestCase):
    """LightdashUser unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
