# coding: utf-8
"""
    Lightdash API

    API spec for Lightdash server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightdash.com
    Generated by: https://openapi-generator.tech
"""
from lightdash_client.paths.org.patch import UpdateOrganization
from lightdash_client.paths.org_projects.get import GetOrganizationProjects
from lightdash_client.paths.org_projects_project_uuid.delete import DeleteOrganizationProject
from lightdash_client.paths.org_users.get import GetOrganizationUsers
from lightdash_client.paths.org_users_user_uuid.delete import DeleteOrganizationUser
from lightdash_client.paths.org_users_user_uuid.patch import UpdateOrganizationMember


class OrganizationApi(
    DeleteOrganizationProject,
    DeleteOrganizationUser,
    GetOrganizationProjects,
    GetOrganizationUsers,
    UpdateOrganization,
    UpdateOrganizationMember,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
