# coding: utf-8
"""
    Lightdash API

    API spec for Lightdash server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightdash.com
    Generated by: https://openapi-generator.tech
"""
from lightdash_client.paths.org_projects.get import GetOrganizationProjects
from lightdash_client.paths.org_projects_project_uuid.delete import DeleteOrganizationProject
from lightdash_client.paths.projects_project_uuid_catalog.get import GetProjectCatalog
from lightdash_client.paths.projects_project_uuid_explores_table_id_run_query.post import RunQuery
from lightdash_client.paths.projects_project_uuid_sql_query.post import RunSqlQuery
from lightdash_client.paths.projects_project_uuid_tables_configuration.get import GetProjectTablesConfiguration
from lightdash_client.paths.projects_project_uuid_tables_configuration.patch import UpdateProjectTablesConfiguration


class ProjectApi(
    DeleteOrganizationProject,
    GetOrganizationProjects,
    GetProjectCatalog,
    GetProjectTablesConfiguration,
    RunQuery,
    RunSqlQuery,
    UpdateProjectTablesConfiguration,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
