# coding: utf-8
"""
    Lightdash API

    API spec for Lightdash server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightdash.com
    Generated by: https://openapi-generator.tech
"""
from lightdash_client.paths.projects_project_uuid_saved.patch import PatchSavedCharts
from lightdash_client.paths.projects_project_uuid_saved.post import PostSavedChart
from lightdash_client.paths.saved_saved_chart_uuid.delete import DeleteSavedChart
from lightdash_client.paths.saved_saved_chart_uuid.get import GetSavedChart
from lightdash_client.paths.saved_saved_chart_uuid.patch import PatchSavedChart
from lightdash_client.paths.saved_saved_chart_uuid_version.post import CreateSavedChartVersion


class SavedApi(
    CreateSavedChartVersion,
    DeleteSavedChart,
    GetSavedChart,
    PatchSavedChart,
    PatchSavedCharts,
    PostSavedChart,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
