# coding: utf-8
"""


    Generated by: https://openapi-generator.tech
"""
import unittest
from unittest.mock import patch

import urllib3

import lightdash_client
from .. import ApiTestMixin
from lightdash_client import api_client
from lightdash_client import configuration
from lightdash_client import schemas
from lightdash_client.paths.saved_saved_chart_uuid import patch  # noqa: E501


class TestSavedSavedChartUuid(ApiTestMixin, unittest.TestCase):
    """
    SavedSavedChartUuid unit test stubs
        Update a saved chart  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = patch.ApiForpatch(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
